### ISSUE TITLE
.get_member keeps returning None in the latest version of Discord API

### ISSUE THREAD

**Issue by Baraa2nassar** [jakeee51/CaliBot#1]
https://github.com/jakeee51/CaliBot/blob/001c4717f9a3c24f9b647476ab11468c945e9adb/cbot.py#L151
@jakeee51 
While I was trying to make the command `/add` work, it kept returning none to the value, so I tried printing the variable and remove each object once per a time and found that` .get_member()` is not being supported. 

I tried to see what solutions or replacements are available in the documentation and it says I have to accept the intent privilege. 

here is the link to the intent documentation 

https://discordpy.readthedocs.io/en/latest/intents.html

the issue output:
`AttributeError: 'NoneType' object has no attribute 'add_roles'

I will just post whatever I find helpful regarding this subject:
`https://discordpy.readthedocs.io/en/latest/api.html#discord.Guild.get_member

Version 1.5 comes with the introduction of intents. This is a radical change in how bots are written. An intent basically allows a bot to subscribe into specific buckets of events. The events that correspond to each intent is documented in the individual attribute of the Intents documentation. Here's an example:
---
where are my members" Why is guild.members/bot.users mostly empty? Why did get_member stop working? Why did on_member_whatever stop working?

This is due to a breaking change introduced by Discord, which started to take effect on 25 Sep 2020 and will be finalized on 7 Oct 2020. Bots will no longer receive certain information from Discord unless they subscribe to those specific Intents. Here is what you must do:

1) Log on to your developer portal at https://discord.com/developers/applications. Click on your bot, then the "Bot" tab on the left, and scroll down to the Privileged Gateway Intents section. There will be two toggles, one for PRESENCE INTENT and one for SERVER MEMBERS INTENT. Toggle the second one on to allow your bot to receive server members. Bots in more than 100 guilds will need to complete the verification process in order to use these intents.

2) Update your discord.py to version 1.5.0. Make sure you're installing it to the correct environment - see ?tag mnf for advice.

3) Modify your discord.Client or commands.Bot constructor call to pass an instance of discord.Intents. Here is an example

**Comment by jakeee51** [comment]
Try
`pip install -U discord.py`
then make sure the latest version is installed with
`pip show discord.py`

Based on the error output you've provided, `.get_member()` is being supported and is returning the `None` data type because the member could not be found based on either the provided user_id or the guild's ID which is set in the line directly above: ` guild = client.get_guild(SERVER_ID)`

Make sure you're using your server ID in the **config.py**. To obtain this ID, simply right click on your Discord Servers name then click **Copy ID**.

Also, the way the `/add` command works is like so:
**/add** ***@User_Name***

**Comment by Baraa2nassar** [comment]
I tried printing our `user_id`, `guilld`, `member`, and `role`

this is the output: 
`user_id is: <re.Match object; span=(8, 26), match='761123575021174784'>`
`guild is Montclair MSA`
`member is None`
`role is None`

`AttributeError: 'NoneType' object has no attribute 'add_roles' the error hasn't changed` and even when I assign `member` to the userID `member= 761123575021174784` that I want to add, just to check if it is running, it outputs `AttributeError: 'int' object has no attribute 'roles'` 

I will keep researching and when I find a solution that works I will update it here.

**Comment by jakeee51** [comment]
The `guild` variable should be a guild object not a string. You get the guild object using the Server's ID which is an integer.
You keep getting the same error because the `add_roles()` is a member function of the **member** class.
For some reason `get_member()` isn't accessing the guild's member list.
